port: 8901

favicon: "favicon.ico"
title: "Aigner"
showservererror: true

database:
  server: "<your database server>"
  name: "<your database name>"
  username: "<your database username>"
  password: "<your database password>"

cookie: 
  persist: true
  secure: false
  lifetime: 24
  samesite: lax
  path: /aigner/

template:
  cached: false
  dir: "data/template/eag2"  
  options:
  - missingkey=error

application:
  pagedir: "data/pages"
  contentdir: "data/content"

hittest: false

logging:
  enabled: true